import type { PermissionRequirement } from '../types/access'

const tenant = (functionality: string, action: string): PermissionRequirement => ({
  functionality,
  action,
  scope: 'tenant',
})

const global = (functionality: string, action: string): PermissionRequirement => ({
  functionality,
  action,
  scope: 'global',
})

export const ACCESS = {
  dashboard: tenant('dashboard', 'read'),
  eventCategoriesRead: tenant('event_categories', 'read'),
  eventCategoriesCreate: tenant('event_categories', 'create'),
  eventCategoriesUpdate: tenant('event_categories', 'update'),
  eventCategoriesDelete: tenant('event_categories', 'delete'),
  eventsRead: tenant('events', 'read'),
  eventsCreate: tenant('events', 'create'),
  eventsUpdate: tenant('events', 'update'),
  eventsDelete: tenant('events', 'delete'),
  eventSessionsRead: tenant('event_sessions', 'read'),
  eventSessionsCreate: tenant('event_sessions', 'create'),
  eventSessionsUpdate: tenant('event_sessions', 'update'),
  eventSessionsDelete: tenant('event_sessions', 'delete'),
  ticketTypesRead: tenant('ticket_types', 'read'),
  ticketTypesCreate: tenant('ticket_types', 'create'),
  ticketTypesUpdate: tenant('ticket_types', 'update'),
  ticketTypesDelete: tenant('ticket_types', 'delete'),
  ticketBatchesRead: tenant('ticket_batches', 'read'),
  ticketBatchesCreate: tenant('ticket_batches', 'create'),
  ticketBatchesUpdate: tenant('ticket_batches', 'update'),
  ticketBatchesDelete: tenant('ticket_batches', 'delete'),
  eventProductsRead: tenant('event_products', 'read'),
  eventProductsCreate: tenant('event_products', 'create'),
  eventProductsUpdate: tenant('event_products', 'update'),
  eventProductsDelete: tenant('event_products', 'delete'),
  venuesRead: tenant('venues', 'read'),
  venuesCreate: tenant('venues', 'create'),
  venuesUpdate: tenant('venues', 'update'),
  venuesDelete: tenant('venues', 'delete'),
  seatsRead: tenant('seats', 'read'),
  seatsCreate: tenant('seats', 'create'),
  seatsUpdate: tenant('seats', 'update'),
  seatsDelete: tenant('seats', 'delete'),
  ordersRead: tenant('orders', 'read'),
  ordersCreate: tenant('orders', 'create'),
  /** Reaproveitada pelo backend em várias ações (edição de itens/parcelas, aprovar/recusar fila online) — ver `.claude/memory/api-patterns.md`. */
  ordersUpdate: tenant('orders', 'update'),
  /** Tela dedicada de vendas online (`/vendas-online`) — permissão própria, independente de `orders,*`. */
  storefrontOrdersRead: tenant('storefront-orders', 'read'),
  storefrontOrdersApprove: tenant('storefront-orders', 'approve'),
  storefrontOrdersCancel: tenant('storefront-orders', 'cancel'),
  storefrontOrdersDispatch: tenant('storefront-orders', 'dispatch'),
  storefrontOrdersUndispatch: tenant('storefront-orders', 'undispatch'),
  storefrontOrdersDeliver: tenant('storefront-orders', 'deliver'),
  storefrontOrdersUndeliver: tenant('storefront-orders', 'undeliver'),
  storefrontOrdersPay: tenant('storefront-orders', 'pay'),
  reportsRead: tenant('reports', 'read'),
  /** Conciliação financeira (roadmap A3.12) — `payments`/`refunds`/`webhook_events` do tenant. */
  financeRead: tenant('finance', 'read'),
  usersRead: tenant('users', 'read'),
  usersCreate: tenant('users', 'create'),
  usersUpdate: tenant('users', 'update'),
  tenantRolesRead: tenant('tenant_roles', 'read'),
  tenantRolesCreate: tenant('tenant_roles', 'create'),
  tenantRolesUpdate: tenant('tenant_roles', 'update'),
  tenantRolesDelete: tenant('tenant_roles', 'delete'),
  tenantUsersRead: tenant('tenant_users', 'read'),
  tenantUsersCreate: tenant('tenant_users', 'create'),
  tenantUsersUpdate: tenant('tenant_users', 'update'),
  tenantUsersDelete: tenant('tenant_users', 'delete'),
  tenantSettingsRead: tenant('tenant_settings', 'read'),
  tenantSettingsUpdate: tenant('tenant_settings', 'update'),
  /** "Minha assinatura" — tela sempre acessível (backend nunca a bloqueia por assinatura suspensa). */
  subscriptionRead: tenant('subscription', 'read'),
  subscriptionUpdate: tenant('subscription', 'update'),
  tenantProfileRead: tenant('tenant-profile', 'read'),
  tenantProfileUpdate: tenant('tenant-profile', 'update'),
  /** Exportar dados (roadmap A1.2) — ZIP com CSVs de clients/products/orders do tenant. */
  tenantProfileExport: tenant('tenant-profile', 'export'),
  /** Central de chamados nativa (roadmap A4, item 17) — functionality `support`, reaproveita actions `read`/`create` já existentes. */
  helpRequestsRead: tenant('support', 'read'),
  helpRequestsCreate: tenant('support', 'create'),
  /** Módulo do contador (lado do tenant) — functionality slug com hífen no backend (`accounting-access`). */
  accountingAccessRead: tenant('accounting-access', 'read'),
  accountingAccessCreate: tenant('accounting-access', 'create'),
  accountingAccessApprove: tenant('accounting-access', 'approve'),
  accountingAccessRevoke: tenant('accounting-access', 'revoke'),
  storefrontUpdate: tenant('storefront', 'update'),
  /** Integrações — API keys + webhook subscriptions (roadmap A6, item 20), functionality única `api-access` pras duas coisas. */
  apiAccessRead: tenant('api-access', 'read'),
  apiAccessCreate: tenant('api-access', 'create'),
  apiAccessUpdate: tenant('api-access', 'update'),
  apiAccessDelete: tenant('api-access', 'delete'),
  /** Só `GET /coupons` exige `storefront:read` (diferente do resto da área de bilheteria online, que usa só `update` para leitura e escrita). */
  storefrontRead: tenant('storefront', 'read'),
  adminUsersRead: global('users', 'read'),
  adminUsersCreate: global('users', 'create'),
  adminUsersUpdate: global('users', 'update'),
  adminUsersDelete: global('users', 'delete'),
  adminGroupsRead: global('groups', 'read'),
  adminGroupsCreate: global('groups', 'create'),
  adminGroupsUpdate: global('groups', 'update'),
  adminGroupsDelete: global('groups', 'delete'),
  adminFunctionalitiesRead: global('functionalities', 'read'),
  adminFunctionalitiesCreate: global('functionalities', 'create'),
  adminFunctionalitiesUpdate: global('functionalities', 'update'),
  adminFunctionalitiesDelete: global('functionalities', 'delete'),
  adminPlansRead: global('plans', 'read'),
  adminPlansCreate: global('plans', 'create'),
  adminPlansUpdate: global('plans', 'update'),
  adminPlansDelete: global('plans', 'delete'),
  adminTenantsRead: global('tenants', 'read'),
  adminTenantsCreate: global('tenants', 'create'),
  adminTenantsUpdate: global('tenants', 'update'),
  adminTenantsDelete: global('tenants', 'delete'),
  adminAuditLogsRead: global('audit_logs', 'read'),
  /** Painel de pendências de pagamento/assinatura (roadmap 2026-07-24) — cross-tenant, exclusivo do staff interno da PegaTicket; functionality própria `payment_admin`, separada de `finance` (tenant-facing). */
  adminPaymentIssuesRead: global('payment_admin', 'read'),
  adminPaymentIssuesUpdate: global('payment_admin', 'update'),
} as const
