import type { PermissionRequirement } from '../types/access'

const tenant = (functionality: string, action: string): PermissionRequirement => ({
  functionality,
  action,
  scope: 'tenant',
})

const global = (functionality: string, action: string): PermissionRequirement => ({
  functionality,
  action,
  scope: 'global',
})

export const ACCESS = {
  dashboard: tenant('dashboard', 'read'),
  clientsRead: tenant('clients', 'read'),
  clientsCreate: tenant('clients', 'create'),
  clientsUpdate: tenant('clients', 'update'),
  clientsDelete: tenant('clients', 'delete'),
  clientCategoriesRead: tenant('client_categories', 'read'),
  clientCategoriesCreate: tenant('client_categories', 'create'),
  clientCategoriesUpdate: tenant('client_categories', 'update'),
  clientCategoriesDelete: tenant('client_categories', 'delete'),
  diasIdeaisRead: tenant('dias_ideais', 'read'),
  diasIdeaisCreate: tenant('dias_ideais', 'create'),
  diasIdeaisUpdate: tenant('dias_ideais', 'update'),
  diasIdeaisDelete: tenant('dias_ideais', 'delete'),
  periodosIdeaisRead: tenant('periodos_ideais', 'read'),
  periodosIdeaisCreate: tenant('periodos_ideais', 'create'),
  periodosIdeaisUpdate: tenant('periodos_ideais', 'update'),
  periodosIdeaisDelete: tenant('periodos_ideais', 'delete'),
  estadosRead: tenant('estados', 'read'),
  estadosCreate: tenant('estados', 'create'),
  estadosUpdate: tenant('estados', 'update'),
  estadosDelete: tenant('estados', 'delete'),
  cidadesRead: tenant('cidades', 'read'),
  cidadesCreate: tenant('cidades', 'create'),
  cidadesUpdate: tenant('cidades', 'update'),
  cidadesDelete: tenant('cidades', 'delete'),
  bairrosRead: tenant('bairros', 'read'),
  bairrosCreate: tenant('bairros', 'create'),
  bairrosUpdate: tenant('bairros', 'update'),
  bairrosDelete: tenant('bairros', 'delete'),
  enderecosRead: tenant('enderecos', 'read'),
  enderecosCreate: tenant('enderecos', 'create'),
  enderecosUpdate: tenant('enderecos', 'update'),
  enderecosDelete: tenant('enderecos', 'delete'),
  productCategoriesRead: tenant('product_categories', 'read'),
  productCategoriesCreate: tenant('product_categories', 'create'),
  productCategoriesUpdate: tenant('product_categories', 'update'),
  productCategoriesDelete: tenant('product_categories', 'delete'),
  productTypesRead: tenant('product_types', 'read'),
  productTypesCreate: tenant('product_types', 'create'),
  productTypesUpdate: tenant('product_types', 'update'),
  productTypesDelete: tenant('product_types', 'delete'),
  productsRead: tenant('products', 'read'),
  productsCreate: tenant('products', 'create'),
  productsUpdate: tenant('products', 'update'),
  productsDelete: tenant('products', 'delete'),
  stockLocationsRead: tenant('stock_locations', 'read'),
  stockLocationsCreate: tenant('stock_locations', 'create'),
  stockLocationsUpdate: tenant('stock_locations', 'update'),
  stockLocationsDelete: tenant('stock_locations', 'delete'),
  stockRead: tenant('stock', 'read'),
  stockCreate: tenant('stock', 'create'),
  ordersRead: tenant('orders', 'read'),
  ordersCreate: tenant('orders', 'create'),
  /** Reaproveitada pelo backend em várias ações (edição de itens/parcelas, aprovar/recusar fila da loja) — ver `.claude/memory/api-patterns.md`. */
  ordersUpdate: tenant('orders', 'update'),
  /** PDV (Fase PDV-1) — functionality `pdv`, actions read/open/close/movement/sell. `read` libera a tela (gate de caixa + venda). */
  pdvRead: tenant('pdv', 'read'),
  pdvOpen: tenant('pdv', 'open'),
  pdvClose: tenant('pdv', 'close'),
  pdvMovement: tenant('pdv', 'movement'),
  pdvSell: tenant('pdv', 'sell'),
  /** Balcão (Fases 1+2) — functionality `balcao`. `read` libera as telas (mesas/comanda/KDS); ações granulares gate por botão. */
  balcaoRead: tenant('balcao', 'read'),
  balcaoCreate: tenant('balcao', 'create'),
  balcaoUpdate: tenant('balcao', 'update'),
  balcaoOpen: tenant('balcao', 'open'),
  balcaoAddItem: tenant('balcao', 'add_item'),
  balcaoPrep: tenant('balcao', 'prep'),
  balcaoClose: tenant('balcao', 'close'),
  /** Tela dedicada de gestão de pedidos da loja (/pedidos-loja) — permissão própria, independente de orders,*. */
  storefrontOrdersRead: tenant('storefront-orders', 'read'),
  storefrontOrdersApprove: tenant('storefront-orders', 'approve'),
  storefrontOrdersCancel: tenant('storefront-orders', 'cancel'),
  storefrontOrdersDispatch: tenant('storefront-orders', 'dispatch'),
  storefrontOrdersUndispatch: tenant('storefront-orders', 'undispatch'),
  storefrontOrdersDeliver: tenant('storefront-orders', 'deliver'),
  storefrontOrdersUndeliver: tenant('storefront-orders', 'undeliver'),
  storefrontOrdersPay: tenant('storefront-orders', 'pay'),
  reportsRead: tenant('reports', 'read'),
  /** Conciliação financeira (roadmap A3.12) — `payments`/`refunds`/`webhook_events` do tenant. */
  financeRead: tenant('finance', 'read'),
  usersRead: tenant('users', 'read'),
  usersCreate: tenant('users', 'create'),
  usersUpdate: tenant('users', 'update'),
  tenantRolesRead: tenant('tenant_roles', 'read'),
  tenantRolesCreate: tenant('tenant_roles', 'create'),
  tenantRolesUpdate: tenant('tenant_roles', 'update'),
  tenantRolesDelete: tenant('tenant_roles', 'delete'),
  tenantUsersRead: tenant('tenant_users', 'read'),
  tenantUsersCreate: tenant('tenant_users', 'create'),
  tenantUsersUpdate: tenant('tenant_users', 'update'),
  tenantUsersDelete: tenant('tenant_users', 'delete'),
  tenantSettingsRead: tenant('tenant_settings', 'read'),
  tenantSettingsUpdate: tenant('tenant_settings', 'update'),
  /** Régua de reativação de cliente (roadmap A5, item 18) — functionality `reactivation`, faixa Ouro+Diamante. */
  reactivationRead: tenant('reactivation', 'read'),
  reactivationUpdate: tenant('reactivation', 'update'),
  /** "Minha assinatura" — tela sempre acessível (backend nunca a bloqueia por assinatura suspensa). */
  subscriptionRead: tenant('subscription', 'read'),
  subscriptionUpdate: tenant('subscription', 'update'),
  taxRulesRead: tenant('tax-rules', 'read'),
  taxRulesCreate: tenant('tax-rules', 'create'),
  taxRulesUpdate: tenant('tax-rules', 'update'),
  taxRulesDelete: tenant('tax-rules', 'delete'),
  tenantProfileRead: tenant('tenant-profile', 'read'),
  tenantProfileUpdate: tenant('tenant-profile', 'update'),
  /** Exportar dados (roadmap A1.2) — ZIP com CSVs de clients/products/orders do tenant. */
  tenantProfileExport: tenant('tenant-profile', 'export'),
  /** Central de chamados nativa (roadmap A4, item 17) — functionality `support`, reaproveita actions `read`/`create` já existentes. */
  supportTicketsRead: tenant('support', 'read'),
  supportTicketsCreate: tenant('support', 'create'),
  /** Módulo do contador (lado do tenant) — functionality slug com hífen no backend (`accounting-access`). */
  accountingAccessRead: tenant('accounting-access', 'read'),
  accountingAccessCreate: tenant('accounting-access', 'create'),
  accountingAccessApprove: tenant('accounting-access', 'approve'),
  accountingAccessRevoke: tenant('accounting-access', 'revoke'),
  storefrontUpdate: tenant('storefront', 'update'),
  /** Integrações — API keys + webhook subscriptions (roadmap A6, item 20), functionality única `api-access` pras duas coisas. */
  apiAccessRead: tenant('api-access', 'read'),
  apiAccessCreate: tenant('api-access', 'create'),
  apiAccessUpdate: tenant('api-access', 'update'),
  apiAccessDelete: tenant('api-access', 'delete'),
  /** Delivery Fase 3 — só `GET /coupons` e `GET /product-promotions` exigem `storefront:read` (diferente do resto da área "Loja online", que usa só `update` p/ leitura e escrita desde a Fase 2). */
  storefrontRead: tenant('storefront', 'read'),
  adminUsersRead: global('users', 'read'),
  adminUsersCreate: global('users', 'create'),
  adminUsersUpdate: global('users', 'update'),
  adminUsersDelete: global('users', 'delete'),
  adminGroupsRead: global('groups', 'read'),
  adminGroupsCreate: global('groups', 'create'),
  adminGroupsUpdate: global('groups', 'update'),
  adminGroupsDelete: global('groups', 'delete'),
  adminFunctionalitiesRead: global('functionalities', 'read'),
  adminFunctionalitiesCreate: global('functionalities', 'create'),
  adminFunctionalitiesUpdate: global('functionalities', 'update'),
  adminFunctionalitiesDelete: global('functionalities', 'delete'),
  adminPlansRead: global('plans', 'read'),
  adminPlansCreate: global('plans', 'create'),
  adminPlansUpdate: global('plans', 'update'),
  adminPlansDelete: global('plans', 'delete'),
  adminTenantsRead: global('tenants', 'read'),
  adminTenantsCreate: global('tenants', 'create'),
  adminTenantsUpdate: global('tenants', 'update'),
  adminTenantsDelete: global('tenants', 'delete'),
  adminAuditLogsRead: global('audit_logs', 'read'),
  /** Painel de pendências de pagamento/assinatura (roadmap 2026-07-24) — cross-tenant, exclusivo do staff interno da Maskats; functionality própria `payment_admin`, separada de `finance` (tenant-facing). */
  adminPaymentIssuesRead: global('payment_admin', 'read'),
  adminPaymentIssuesUpdate: global('payment_admin', 'update'),
} as const
